//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestMate.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST MATE® VERSION 4.0.
        /// </summary>
        public static string aboutLabel1 {
            get {
                return ResourceManager.GetString("aboutLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mate® is a mobile self-study system, designed to assist you in achieving your educational and professional goals by allowing you to study what you want, when and where you want. Why study alone?.
        /// </summary>
        public static string aboutLabel2 {
            get {
                return ResourceManager.GetString("aboutLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil or criminal penalties, and will be prosecuted under the maximum extent possible under law..
        /// </summary>
        public static string aboutLabel3 {
            get {
                return ResourceManager.GetString("aboutLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Test Mate....
        /// </summary>
        public static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clicked {0}!.
        /// </summary>
        public static string clickTestMessage {
            get {
                return ResourceManager.GetString("clickTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 1993-{0} Rob Garcia. All rights reserved..
        /// </summary>
        public static string copyrightLabel {
            get {
                return ResourceManager.GetString("copyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a Test....
        /// </summary>
        public static string downloadButton {
            get {
                return ResourceManager.GetString("downloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Study Alone?.
        /// </summary>
        public static string mainSubtitle {
            get {
                return ResourceManager.GetString("mainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO TEST MATE!.
        /// </summary>
        public static string mainTitle {
            get {
                return ResourceManager.GetString("mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open that file!.
        /// </summary>
        public static string openFileErrorMessage {
            get {
                return ResourceManager.GetString("openFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the test file contans a list of key terms, Test Mate can display the term as your question and a set of possible definitions as your choices (default); display the definition as your question and a set of possible key terms as your choices; or randomly display terms or definitions as your questions.\nYour current setting is shown below; click on the setting to change its value..
        /// </summary>
        public static string settingsKeyTermsDisplay {
            get {
                return ResourceManager.GetString("settingsKeyTermsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mate can provide immediate feedback after you choose an answer (default) or provide you feedback after you have completed the test.\nYour current setting is shown below; click on the setting to change its value..
        /// </summary>
        public static string settingsProvideFeedback {
            get {
                return ResourceManager.GetString("settingsProvideFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mate can present your test questions in the order that it read them from the test file (default) or in a random order.\nYour current setting is shown below; click on the setting to change its value..
        /// </summary>
        public static string settingsQuestionOrder {
            get {
                return ResourceManager.GetString("settingsQuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings....
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a New Test....
        /// </summary>
        public static string startTitle {
            get {
                return ResourceManager.GetString("startTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch language to Spanish.
        /// </summary>
        public static string swtichLanguageButton {
            get {
                return ResourceManager.GetString("swtichLanguageButton", resourceCulture);
            }
        }
    }
}
