//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestMate.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST MATE® VERSION 4.0.
        /// </summary>
        public static string AboutLabel1 {
            get {
                return ResourceManager.GetString("AboutLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mate® is a mobile self-study system, designed to assist you in achieving your educational and professional goals by allowing you to study what you want, when and where you want. Why study alone?.
        /// </summary>
        public static string AboutLabel2 {
            get {
                return ResourceManager.GetString("AboutLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil or criminal penalties, and will be prosecuted under the maximum extent possible under law..
        /// </summary>
        public static string AboutLabel3 {
            get {
                return ResourceManager.GetString("AboutLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to access the online user&apos;s manual..
        /// </summary>
        public static string AboutOnlineManualButton {
            get {
                return ResourceManager.GetString("AboutOnlineManualButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Test Mate....
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Study Alone?.
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO TEST MATE!.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct..
        /// </summary>
        public static string ButtonCorrect {
            get {
                return ResourceManager.GetString("ButtonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ButtonQuit {
            get {
                return ResourceManager.GetString("ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ButtonReview {
            get {
                return ResourceManager.GetString("ButtonReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect..
        /// </summary>
        public static string ButtonWrong {
            get {
                return ResourceManager.GetString("ButtonWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clicked {0}!.
        /// </summary>
        public static string ClickTestMessage {
            get {
                return ResourceManager.GetString("ClickTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 1993-{0} Rob Garcia. All rights reserved..
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download and save test: {0}.
        /// </summary>
        public static string DownloadErrorMessage {
            get {
                return ResourceManager.GetString("DownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a test to download....
        /// </summary>
        public static string DownloadLabel {
            get {
                return ResourceManager.GetString("DownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test downloaded and saved!.
        /// </summary>
        public static string DownloadSuccessMessage {
            get {
                return ResourceManager.GetString("DownloadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a Test....
        /// </summary>
        public static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open that file!.
        /// </summary>
        public static string OpenFileErrorMessage {
            get {
                return ResourceManager.GetString("OpenFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide feedback immediately..
        /// </summary>
        public static string ProvideFeedbackOption1 {
            get {
                return ResourceManager.GetString("ProvideFeedbackOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide feedback after the test is complete..
        /// </summary>
        public static string ProvideFeedbackOption2 {
            get {
                return ResourceManager.GetString("ProvideFeedbackOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default question order..
        /// </summary>
        public static string QuestionOrderOption1 {
            get {
                return ResourceManager.GetString("QuestionOrderOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the order of the questions..
        /// </summary>
        public static string QuestionOrderOption2 {
            get {
                return ResourceManager.GetString("QuestionOrderOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsCancelButton {
            get {
                return ResourceManager.GetString("SettingsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the test contains key terms, would you like to match definitions to terms, match terms to definitions, or to mix it up?.
        /// </summary>
        public static string SettingsKeyTermsDisplayLabel {
            get {
                return ResourceManager.GetString("SettingsKeyTermsDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file not found!
        ///Configuration reset and saved..
        /// </summary>
        public static string SettingsMissingErrorMessage {
            get {
                return ResourceManager.GetString("SettingsMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like feedback after each a question or after the test is complete?.
        /// </summary>
        public static string SettingsProvideFeedbackLabel {
            get {
                return ResourceManager.GetString("SettingsProvideFeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to answer test questions in the default order or in a random order?.
        /// </summary>
        public static string SettingsQuestionOrderLabel {
            get {
                return ResourceManager.GetString("SettingsQuestionOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cannot access the settings file: {0}
        ///Please contact Test Mate for assistance..
        /// </summary>
        public static string SettingsReadErrorMessage {
            get {
                return ResourceManager.GetString("SettingsReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string SettingsSaveButton {
            get {
                return ResourceManager.GetString("SettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Settings were not saved: {0} Please contact Test Mate for assistance..
        /// </summary>
        public static string SettingsSaveErrorMessage {
            get {
                return ResourceManager.GetString("SettingsSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string SettingsSaveSuccessMessage {
            get {
                return ResourceManager.GetString("SettingsSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings....
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string StartDelete {
            get {
                return ResourceManager.GetString("StartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        public static string StartDeleteConfirm {
            get {
                return ResourceManager.GetString("StartDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete test: {0}.
        /// </summary>
        public static string StartDeleteErrorMessage {
            get {
                return ResourceManager.GetString("StartDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete test: File not found..
        /// </summary>
        public static string StartDeleteNotFoundMessage {
            get {
                return ResourceManager.GetString("StartDeleteNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted..
        /// </summary>
        public static string StartDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("StartDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a test....
        /// </summary>
        public static string StartSubtitle {
            get {
                return ResourceManager.GetString("StartSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a New Test....
        /// </summary>
        public static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the key term for the question and a set of possible definitions for the choices..
        /// </summary>
        public static string TermDisplayOption1 {
            get {
                return ResourceManager.GetString("TermDisplayOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the definition for the question and a set of possible key terms for the choices..
        /// </summary>
        public static string TermDisplayOption2 {
            get {
                return ResourceManager.GetString("TermDisplayOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly use key terms or definitions for the questions..
        /// </summary>
        public static string TermDisplayOption3 {
            get {
                return ResourceManager.GetString("TermDisplayOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection!.
        /// </summary>
        public static string TestBadSelectionMessage {
            get {
                return ResourceManager.GetString("TestBadSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the beginning of the test..
        /// </summary>
        public static string TestBeginningMessage {
            get {
                return ResourceManager.GetString("TestBeginningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the end of the test..
        /// </summary>
        public static string TestEndMessage {
            get {
                return ResourceManager.GetString("TestEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this test?.
        /// </summary>
        public static string TestQuitMessage {
            get {
                return ResourceManager.GetString("TestQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score was {0:0.00}% ({1} out of {2}).
        ///Would you like to see your results in more detail?.
        /// </summary>
        public static string TestScoreMessage {
            get {
                return ResourceManager.GetString("TestScoreMessage", resourceCulture);
            }
        }
    }
}
